### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by willycornelissen** [CPJKU/onset_db#1]
Dear Mr. Bock,

I am working on music onset detection to get my master degree and I would like to know it is possible to have the dataset cited in some papers you wrote. This dataset (more than 25k onsets) is mentioned in this repo and I the instruction is to contact you for further information.

How can I download the dataset? Is it available somewhere?

**Comment by superbock** [comment]
You can download the audio, annotations and splits used from here:

https://drive.google.com/file/d/0B-MfhNTg9c5eTGJ6X0FOd0xDSWs/view?usp=sharing
https://drive.google.com/file/d/0B-MfhNTg9c5eUV9DRVluNjdTOGs/view?usp=sharing
https://drive.google.com/file/d/0B-MfhNTg9c5eeDktWUpjeUF3VkU/view?usp=sharing

This is the cleaned version of the dataset. A couple of files were removed since they were basically duplicates of others at different volume levels. 

There are more than 321 audio files and annotations, these were made later on. Please ignore them for now, since the annotations for them are not ready to be released yet. The 321 annotations and the 8 pre-defined splits are those used in the latest papers.

**Comment by willycornelissen** [comment]
Thank you Sebastian. You are doing an excellent job and inspiring many students all over the world. Congratulations!

**Comment by willycornelissen** [comment]
Hi Mr. Bock!

Did you use this dataset you shared with me to train the models used on Madmom? If I use CNNOnsetDetector as detection tool, can I use this dataset as test set?
